apiVersion: apps/v1
kind: Deployment
metadata:
  name: qqqq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qqqq
  template:
    metadata:
      labels:
        app: qqqq
    spec:
      containers:
      - image: okteto.dev/qqqq:latest
        name: qqqq
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2ef6aa55-6661-461c-9ec9-1ef917588b66"
        - name: Vless_Path
          value: "/l555"
        - name: Vmess_UUID
          value: "2ef6aa55-6661-461c-9ec9-1ef917588b66"
        - name: Vmess_Path
          value: "/m555"
        - name: Share_Path
          value: "/v2link"
